fundacionpet-rest/core/urls.py
# from django.conf.urls import url
# from django.conf import settings
# from django.views.static import serve
from django.urls import path
from .views import index,blog,carro,checkout,compare,error_404,\
                    galeria,nosotros,\
                    wishlist,tiendafor,contacto1,listar_producto,agregar_producto,\
                    modificar_producto,eliminar_producto,registro_usuario,mi_cuenta,\
                    mi_cuenta_CRUD,adopcion_mascota,listar_mascota,agregar_mascota,\
                    modificar_mascota,eliminar_mascota,contacto_adopcion,agregar_suscripcion,\
                    listar_suscripciones,agregar_suscripciones,modificar_suscripciones,eliminar_suscripciones,order

urlpatterns = [
    path('', index, name="index"),
    path('adopcion_mascota/', adopcion_mascota, name="adopcion_mascota"),
    path('contacto_adopcion/', contacto_adopcion, name="contacto_adopcion"),
    path('error_404/', error_404, name="error_404"),
    path('galeria/', galeria, name="galeria"),
    path('nosotros/', nosotros, name="nosotros"),
    path('tiendafor/', tiendafor, name="tiendafor"),
    path('contacto1/', contacto1, name="contacto1"),
    path('blog/', blog, name="blog"),
    
    path('registro_usuario/', registro_usuario, name="registro_usuario"),
    path('mi_cuenta/', mi_cuenta, name="mi_cuenta"),
    path('mi_cuenta_CRUD/', mi_cuenta_CRUD, name="mi_cuenta_CRUD"),

    path('carro/', carro, name="carro"),
    path('checkout/', checkout, name="checkout"),
    path('compare/', compare, name="compare"),
    path('wishlist/', wishlist, name="wishlist"),

    path('listar_producto/', listar_producto, name="listar_producto"),
    path('agregar_producto/', agregar_producto, name="agregar_producto"),
    path('modificar_producto/<id>/', modificar_producto, name="modificar_producto"),
    path('eliminar_producto/<id>/', eliminar_producto, name="eliminar_producto"),
 
    path('listar_mascota/', listar_mascota, name="listar_mascota"),
    path('agregar_mascota/', agregar_mascota, name="agregar_mascota"),
    path('modificar_mascota/<id>/', modificar_mascota, name="modificar_mascota"),
    path('eliminar_mascota/<id>/', eliminar_mascota, name="eliminar_mascota"),

    path('agregar_suscripcion/', agregar_suscripcion, name="agregar_suscripcion"),

    path('listar_suscripciones/', listar_suscripciones, name="listar_suscripciones"),
    path('agregar_suscripciones/', agregar_suscripciones, name="agregar_suscripciones"),
    path('modificar_suscripciones/<id>/', modificar_suscripciones, name="modificar_suscripciones"),
    path('eliminar_suscripciones/<id>/', eliminar_suscripciones, name="eliminar_suscripciones"),

    path('order/', order, name="order"),




]

fundacionpet-rest/fundacionpet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

#Importar las VISTAS del TOKEN para validar los INICIO DE SESION
from rest_framework.authtoken import views
from rest_api.viewslogin import Login, Logout
from core.views import agregar_products, eliminar_products, restar_products, limpiar_carrito,agregar_productsCart, \
                        agregar_productsW, eliminar_productsW, restar_productsW, limpiar_carritoW,agregar_productsWMVC,\
                        agregar_productsC, eliminar_productsC, restar_productsC, limpiar_carritoC,agregar_productsCMVC



urlpatterns = [
    #Define las vistas de 127.1.8000/admin
    path('admin/', admin.site.urls),
    
    #Define las vistas de 127.1.800:
    path('', include('core.urls')),
    path('', include('weather.urls')),

    #Enlazar el archivo de ruta de la APLICACION 'rest_api' con la del PROYECTO
    path('api/', include(('rest_api.urls','rest_api'))),
   
    #path('api/', include(('api.urls','api'))),

    path('accounts/', include('django.contrib.auth.urls')),
    #path('api/login', login, name="login"),
    

    #Crear la ruta que genere los TOKENS
    # Al hacer una peticion a esta VISTA, responde con un TOKEN creado para el usu correspondiente
    #Esto permite solo el METODO POST. Para generar un TOKEN debe enviado por via POST
    path('api_generate_token/', views.obtain_auth_token),

    #Ruta Login
    path('login/', Login.as_view(), name='login'),
    #Ruta Logout
    path('logout/', Logout.as_view(), name='logout'),
    
    path('agregar/<int:producto_id>/', agregar_products, name="Add"),
    path('agregar2/<int:producto_id>/', agregar_productsCart, name="agregaCarro"),
    path('eliminar/<int:producto_id>/', eliminar_products, name="Del"),
    path('restar/<int:producto_id>/', restar_products, name="Sub"),
    path('limpiar/', limpiar_carrito, name="CLS"),


    path('agregarW/<int:producto_id>/', agregar_productsW, name="agregarW"),
    path('agregarW2/<int:producto_id>/', agregar_productsWMVC, name="agregarWMVC"),
    path('eliminarW/<int:producto_id>/', eliminar_productsW, name="eliminarW"),
    path('restarW/<int:producto_id>/', restar_productsW, name="restarW"),
    path('limpiarW/', limpiar_carritoW, name="limpiarW"),


    path('agregarC/<int:producto_id>/', agregar_productsC, name="agregarC"),
    path('agregarC2/<int:producto_id>/', agregar_productsCMVC, name="agregarCMVC"),
    path('eliminarC/<int:producto_id>/', eliminar_productsC, name="eliminarC"),
    path('restarC/<int:producto_id>/', restar_productsC, name="restarC"),
    path('limpiarC/', limpiar_carritoC, name="limpiarC"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fundacionpet-rest/core/models.py
from random import choices
from unittest.util import _MAX_LENGTH
from django.db import models
from pyexpat import model
from django.conf import settings
from django.contrib.auth.models import User
from django.utils import timezone


#Crear un MODELO para PERSONAS
class Persona(models.Model):
    #Crear los ATRIBUTOS
    id = models.AutoField(primary_key=True)
    nombre = models.CharField('Nombre', max_length=100)
    apellido = models.CharField('Apellido', max_length=200)

    #Vista por defecto para cada instancia del MODELO PERSONA
    def __str__(self):
        #Se formatea la cadena, muestra primero el apellido
        return '{0},{1}'.format(self.apellido, self.nombre) 


# Create your models here.
#TABLAS PROYECTO
class Marca(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre

class Producto(models.Model):
    nombre = models.CharField(max_length=50)
    precio = models.IntegerField()
    precio_oferta = models.IntegerField()
    stock = models.IntegerField(null=True)
    descripcion = models.TextField()
    nuevo = models.BooleanField()
    marca = models.ForeignKey(Marca, on_delete=models.PROTECT)
    imagen = models.ImageField(upload_to="productos", null=True)

    def __str__(self):
        return self.nombre





    
#FORMULARIO CONTACTO
opciones_consulta = [
    [0, "Consulta"],
    [1, "Reclamo"],
    [2, "Sugerencias"],
    [3, "Felicitaciones"]
]

class Contacto1(models.Model):
    nombre = models.CharField(max_length=50)
    correo = models.EmailField()
    tipo_consulta = models.IntegerField(choices=opciones_consulta)
    mensaje = models.TextField()
    #avisos = models.BooleanField()

    def __str__(self):
        return self.nombre


opciones_tamanio = [
    [0, "Pequeño"],
    [1, "Mediano"],
    [2, "Grande"],
]


opciones_sexo = [
    [0, "Macho"],
    [1, "Hembra"],
]

class Adopcion(models.Model):
    nombre = models.CharField(max_length=50)
    descripcion = models.TextField()
    tamanio = models.IntegerField(choices=opciones_tamanio)
    edad = models.IntegerField()
    sexo = models.IntegerField(choices=opciones_sexo)
    microchip = models.CharField(max_length=50)
    vacunado = models.BooleanField()
    imagen = models.ImageField(upload_to="adopciones", null=True)

    def __str__(self):
        return self.nombre


opciones_adopcion = [
    [0, "Adoptar"],
    [1, "Apadrinar"],
]

class ContactoAdopcion(models.Model):
    nombre = models.CharField(max_length=50)
    correo = models.EmailField()
    tipo_adopcion = models.IntegerField(choices=opciones_adopcion)
    mensaje = models.TextField()
    suscripcion = models.BooleanField()

    def __str__(self):
        return self.nombre


class Suscripcion(models.Model):
    email = models.EmailField(User,null=True)
    suscripcion = models.BooleanField()
    fecha_vigencia = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.email
User

fundacionpet-rest/core/forms.py
from dataclasses import fields
from pickle import TRUE
from pyexpat import model
from tabnanny import verbose
from django import forms
from .models import Contacto1, Producto, Adopcion,ContactoAdopcion,Suscripcion
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.conf import settings

#Formulario Contacto1
class Contacto1Form(forms.ModelForm):
    #Validando los campos
    nombre = forms.CharField(min_length=3, max_length=50)

    class Meta:
        model = Contacto1
        #fields = ["nombre", "correo", "tipo_consulta", "mensaje", "avisos"]
        fields = '__all__'

#Formulario para agregar producto
class ProductoForm(forms.ModelForm):

    #Validando los campos
    nombre = forms.CharField(min_length=3, max_length=50)
    precio = forms.IntegerField(min_value=1000, max_value=1200000)
    precio_oferta = forms.IntegerField(min_value=0, max_value=1500000)
    stock = forms.IntegerField(min_value=1, max_value=300)
    nuevo = forms.BooleanField(required=False)

    class Meta:
        model = Producto
        fields = '__all__'
    
        #Para las fechas de agregar producto
        # widgets = {
        #     "fecha_fabricacion": forms.SelectDateWidget()
        # }

#Formulario Registro Usuario -> Para validar sus campos
class RegistroUserCreationForm(UserCreationForm):

    #Validando los campos
    first_name = forms.CharField(min_length=3, max_length=50,label="Nombre") 
    last_name = forms.CharField(min_length=3, max_length=50,label="Apellido")
    email = forms.CharField(min_length=3, max_length=50,label="Correo")

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email','password1', 'password2']


class AdopcionForm(forms.ModelForm):
    opciones_tamaño = [
        ['', '--'],
        ['0', 'Pequeño'],
        ['1', 'Mediano'],
        ['2', 'Grande'],
    ]
    opciones_sexo = [
    ['', '--'],
    [0, "Macho"],
    [1, "Hembra"],
    ]

    nombre = forms.CharField(min_length=2, max_length=50,label="Nombre",help_text="Ingrese el nombre de la mascota en adopción")
    tamanio = forms.ChoiceField(label="Tamaño",choices=opciones_tamaño)
    edad = forms.IntegerField(min_value=1, max_value=50,label="Edad",help_text="Ingrese edad entre 1 y 50 años")
    sexo = forms.ChoiceField(label="Sexo",choices=opciones_sexo)
    microchip = forms.CharField(min_length=5, max_length=50,label="N° Microchip",help_text="Ingrese N° de MicroChip")
    vacunado = forms.BooleanField(required=False,label="¿Vacunas al día?")
    
    class Meta:
        model = Adopcion
        fields = '__all__'



#Formulario ContactoADOPCION
class ContactoAdopcionForm(forms.ModelForm):
    #Validando los campos
    nombre = forms.CharField(min_length=3, max_length=50)
    suscripcion = forms.BooleanField(required=False,label="¿Desea suscribirse con ayuda?")

    class Meta:
        model = ContactoAdopcion
        #fields = ["nombre", "correo", "tipo_consulta", "mensaje", "avisos"]
        fields = '__all__'
        

class SuscripcionForm(forms.ModelForm):
    email = forms.EmailField(label="Porfavor ingrese un correo de usuario registrado")
    suscripcion = forms.BooleanField(required=False,label="¿Desea suscribirse a una donación?")

    class Meta:
        model = Suscripcion
        fields =  ['email','suscripcion' ]
        

fundacionpet-rest/core/templates/core/crud/agregar_mascota.html
{% extends 'core/base_1.html'%} {% load static %} {% block js %} {% endblock %} {% block css %} {% endblock %} {% block contenido %}
<!--INICIO: TERCERA barra -->
<nav class="navbar navbar-expand-lg navbar-light ftco_navbar bg-light ftco-navbar-light p-3" id="ftco-navbar">
    <div class="container mt-2 align-content-center">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="fa fa-bars"></span> Menu
        </button>

        <form action="#" class="searchform order-lg-last mt-3">
            <div class="form-group d-flex">
                <!-- <input type="text" class="form-control pl-3" placeholder="Search">
                <button type="submit" placeholder="" class="form-control search"><span class="fa fa-search"></span></button> -->
                <p class="mb-1">Llamanos ahora: <br><i class="icon ion-ios-telephone colorNaranja py-1 px-2 mx-2 text-light" width="25px"></i><span class="font-weight-mid pt-1">+569 1234 5478</span></p>
            </div>
        </form>

        <div class="collapse navbar-collapse h5" id="ftco-nav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item mx-2"><a href="{% url 'index' %}" class="nav-link text-dark">Home</a></li>
                <li class="nav-item mx-2"><a href="{% url 'nosotros' %}" class="nav-link text-dark">Nosotros</a></li>
                <li class="nav-item mx-2"><a href="{% url 'galeria' %}" class="nav-link text-dark">Galeria</a></li>
                <li class="nav-item mx-2"><a href="{% url 'adopcion_mascota' %}" class="nav-link text-dark">Adopción</a></li>
                <li class="nav-item mx-2"><a href="{% url 'tiendafor' %}" class="nav-link text-dark">Tienda</a></li>
                <li class="nav-item mx-2"><a href="{% url 'contacto1' %}" class="nav-link text-dark">Contacto</a></li>
            </ul>
        </div>
    </div>
</nav>
<!--FIN: TERCERA barra -->

<!-- INICIO: Banner -->
<nav aria-label="breadcrumb" class="breadcrumb-wrapper">
    <div class="container">
        <ol class="breadcrumb pt-4">
            <li class="breadcrumb-item h5"><strong><a href="{% url 'mi_cuenta_CRUD' %}">< Volver al menú</a></strong></li>
        </ol>
    </div>
</nav>
<!-- FIN: Banner -->

<div class="container">
    <div class="col-12 col-md-6 offset-md-3">
        <h2 class="h1-responsive font-weight-bold text-center my-4">Agregar Mascota en Adopción</h2>
        <hr class="bg-dark">
    </div>
</div>

<div class="row">
    <div class="col-12 col-md-6 offset-md-3">

        {% load crispy_forms_tags %}

        <div class="card">
            <div class="card-body">

                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %} {{ form | crispy }}

                    <br>
                    <div class="text-center mx-3 mb-5">
                        <a href="{% url 'mi_cuenta_CRUD' %}" class="btn colorNaranja text-light mx-2 my-2">Cancelar</a>
                        <!-- <input type="reset" value="Cancelar" class="btn colorNaranja text-light mx-2 my-2"> -->
                        <button type="submit" id="btnEnviar" class="button btn colorVerde text-light mx-2 my-2">Enviar</button>
                    </div>
                </form>

                {{ mensaje }}

            </div>
        </div>

    </div>
</div>
{% endblock %}

fundacionpet-rest/core/templates/core/crud/listar_mascota.html
{% extends 'core/base_1.html'%} {% load static %} {% block css %} {% endblock %} {% block js %}
<script>
    function eliminarProducto(id) {
        Swal.fire({
                "title": "¿Estas segur@?",
                "text": "Esta acción no se puede deshacer",
                "icon": "question",
                "showCancelButton": true,
                "cancelButtonText": "No, Cancelar",
                "confirmButtonText": "Si, Eliminar",
                "reverseButtons": true,
                "confirmButtonColor": "#dc3545"
            })
            .then(function(result) {
                if (result.isConfirmed) {
                    window.location.href = "/eliminar_mascota/" + id + "/"
                }
            })

    }
</script>
{% endblock %} {% load humanize %} {% block contenido %}
<!--INICIO: TERCERA barra -->
<nav class="navbar navbar-expand-lg navbar-light ftco_navbar bg-light ftco-navbar-light p-3" id="ftco-navbar">
    <div class="container mt-2 align-content-center">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="fa fa-bars"></span> Menu
        </button>

        <form action="#" class="searchform order-lg-last mt-3">
            <div class="form-group d-flex">
                <!-- <input type="text" class="form-control pl-3" placeholder="Search">
                <button type="submit" placeholder="" class="form-control search"><span class="fa fa-search"></span></button> -->
                <p class="mb-1">Llamanos ahora: <br><i class="icon ion-ios-telephone colorNaranja py-1 px-2 mx-2 text-light" width="25px"></i><span class="font-weight-mid pt-1">+569 1234 5478</span></p>
            </div>
        </form>

        <div class="collapse navbar-collapse h5" id="ftco-nav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item mx-2"><a href="{% url 'index' %}" class="nav-link text-dark">Home</a></li>
                <li class="nav-item mx-2"><a href="{% url 'nosotros' %}" class="nav-link text-dark">Nosotros</a></li>
                <li class="nav-item mx-2"><a href="{% url 'galeria' %}" class="nav-link text-dark">Galeria</a></li>
                <li class="nav-item mx-2"><a href="{% url 'adopcion_mascota' %}" class="nav-link text-dark">Adopción</a></li>
                <li class="nav-item mx-2"><a href="{% url 'tiendafor' %}" class="nav-link text-dark">Tienda</a></li>
                <li class="nav-item mx-2"><a href="{% url 'contacto1' %}" class="nav-link text-dark">Contacto</a></li>
            </ul>
        </div>
    </div>
</nav>
<!--FIN: TERCERA barra -->

<!-- INICIO: Banner -->
<nav aria-label="breadcrumb" class="breadcrumb-wrapper">
    <div class="container">
        <ol class="breadcrumb pt-4">
            <li class="breadcrumb-item h5"><strong><a href="{% url 'mi_cuenta_CRUD' %}">< Volver al menú</a></strong></li>
        </ol>
    </div>
</nav>
<!-- FIN: Banner -->


<div class="container my-5">
    <div class="col-12 col-md-8 offset-md-2 my-5">
        <h2 class="h1-responsive font-weight-bold text-center my-4">Listado de Mascotas en Adopción</h2>
        <hr class="bg-dark">
    </div>

    <div class="row">
        <div class="col-12 col-md-12 ">

            <table class="table table-responsive-lg mb-5">
                <thead class="text-justify colorGris text-light">
                    <tr>
                        <th>Mascota</th>
                        <th>Nombre</th>
                        <th>Descripcion</th>
                        <th>Tamaño</th>
                        <th>Sexo</th>
                        <th>Edad</th>
                        <th class="text-center">N° Microchip</th>
                        <th class="text-center">¿Vacunado?</th>
                        <th class="text-center">Opciones</th>
                    </tr>
                </thead>

                {% for pro in mascotaAdopcion %}
                <tbody>
                    <tr>
                        {% if pro.imagen %}
                        <td><img src="{{ pro.imagen.url }}" alt="Imagen producto" class="text-center"></td>
                        {% endif %}
                        <td>{{ pro.nombre | title }}</td>
                        <td>{{ pro.descripcion | title }}</td>
                        <td>{% if pro.tamanio == 0 %} Pequeño {% elif pro.tamanio == 1 %} Mediano {% else %} Grande {% endif %}</td>
                        <td>{% if pro.sexo == 0 %} Macho  {% else %} Hembra {% endif %}</td>
                        <td class="text-center">{{ pro.edad }}</td>
                        <td class="text-center">{{ pro.microchip }}</td>
                        <td class="text-center">
                            {% if pro.vacunado %} Si {% else %} No {% endif %}
                        </td>
                        <td class="text-center">
                            {% if perms.fundacionpet.change_adopcion %}
                            <a href="{% url 'modificar_mascota' pro.id %}" class="btn colorVerde text-light m-1">Modificar</a>
                            {% endif %}
                            {% if perms.fundacionpet.delete_adopcion %}
                            <a href="#" onclick="eliminarProducto({{ pro.id }})" class="btn colorNaranja text-light m-1">Eliminar</a>
                            {% endif %}
                        </td>
                    </tr>
                </tbody>
                {% endfor %}
            </table>

            <!-- Importar el Paginador -->
            <hr class="my-5">
            <div>
                {% include 'core/paginacion.html' %}
            </div>

        </div>
    </div>
</div>
{% endblock %}

fundacionpet-rest/core/templates/core/crud/listar_producto.html
{% extends 'core/base_1.html'%} {% load static %} {% block css %} {% endblock %} {% block js %}
<script>
    function eliminarProducto(id) {
        Swal.fire({
                "title": "¿Estas segur@?",
                "text": "Esta acción no se puede deshacer",
                "icon": "question",
                "showCancelButton": true,
                "cancelButtonText": "No, Cancelar",
                "confirmButtonText": "Si, Eliminar",
                "reverseButtons": true,
                "confirmButtonColor": "#dc3545"
            })
            .then(function(result) {
                if (result.isConfirmed) {
                    window.location.href = "/eliminar_producto/" + id + "/"
                }
            })

    }
</script>
{% endblock %} {% load humanize %} {% block contenido %}
<!--INICIO: TERCERA barra -->
<nav class="navbar navbar-expand-lg navbar-light ftco_navbar bg-light ftco-navbar-light p-3" id="ftco-navbar">
    <div class="container mt-2 align-content-center">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="fa fa-bars"></span> Menu
        </button>

        <form action="#" class="searchform order-lg-last mt-3">
            <div class="form-group d-flex">
                <!-- <input type="text" class="form-control pl-3" placeholder="Search">
                <button type="submit" placeholder="" class="form-control search"><span class="fa fa-search"></span></button> -->
                <p class="mb-1">Llamanos ahora: <br><i class="icon ion-ios-telephone colorNaranja py-1 px-2 mx-2 text-light" width="25px"></i><span class="font-weight-mid pt-1">+569 1234 5478</span></p>
            </div>
        </form>

        <div class="collapse navbar-collapse h5" id="ftco-nav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item mx-2"><a href="{% url 'index' %}" class="nav-link text-dark">Home</a></li>
                <li class="nav-item mx-2"><a href="{% url 'nosotros' %}" class="nav-link text-dark">Nosotros</a></li>
                <li class="nav-item mx-2"><a href="{% url 'galeria' %}" class="nav-link text-dark">Galeria</a></li>
                <li class="nav-item mx-2"><a href="{% url 'adopcion_mascota' %}" class="nav-link text-dark">Adopción</a></li>
                <li class="nav-item mx-2"><a href="{% url 'tiendafor' %}" class="nav-link text-dark">Tienda</a></li>
                <li class="nav-item mx-2"><a href="{% url 'contacto1' %}" class="nav-link text-dark">Contacto</a></li>
            </ul>
        </div>
    </div>
</nav>
<!--FIN: TERCERA barra -->

<!-- INICIO: Banner -->
<nav aria-label="breadcrumb" class="breadcrumb-wrapper">
    <div class="container">
        <ol class="breadcrumb pt-4">
            <li class="breadcrumb-item h5"><strong><a href="{% url 'mi_cuenta_CRUD' %}">< Volver al menú</a></strong></li>
        </ol>
    </div>
</nav>
<!-- FIN: Banner -->


<div class="container my-5">
    <div class="col-12 col-md-8 offset-md-2 my-5">
        <h2 class="h1-responsive font-weight-bold text-center my-4">Listado de Productos</h2>
        <hr class="bg-dark">
    </div>

    <div class="row">
        <div class="col-12 col-md-12">

            <table class="table table-responsive-lg mb-5">
                <thead class="text-justify colorGris text-light">
                    <tr>
                        <th>Producto</th>
                        <th>Nombre</th>
                        <th>Precio</th>
                        <th>Precio oferta</th>
                        <th class="text-center">Stock</th>
                        <!-- <th>Descripcion</th> -->
                        <th class="text-center">Nuevo</th>
                        <th class="text-center">Marca</th>
                        <!-- <th class="text-center">Fecha elaboración</th> -->
                        <th class="text-center">Opciones</th>
                    </tr>
                </thead>

                {% for pro in productosTienda %}
                <tbody>
                    <tr>
                        {% if pro.imagen %}
                        <td><img src="{{ pro.imagen.url }}" alt="Imagen producto" class="text-center"></td>
                        {% endif %}
                        <td>{{ pro.nombre | title }}</td>
                        <td class="text-center">${{ pro.precio | intcomma }}</td>
                        <td class="text-center">${{ pro.precio_oferta | intcomma }}</td>
                        <td class="text-center">{{ pro.stock }}</td>
                        <!-- <td>{{ pro.descripcion }}</td> -->
                        <td class="text-center">
                            {% if pro.nuevo %} Si {% else %} No {% endif %}
                        </td>
                        <td class="text-center">{{ pro.marca | title }}</td>
                        <!-- <td>{{ pro.fecha_elaboracion }}</td> -->
                        <td class="text-center">
                            {% if perms.fundacionpet.change_producto %}
                            <a href="{% url 'modificar_producto' pro.id %}" class="btn colorVerde text-light m-1">Editar</a>
                            {% endif %}
                            {% if perms.fundacionpet.delete_producto %}
                            <a href="#" onclick="eliminarProducto({{ pro.id }})" class="btn colorNaranja text-light m-1">Eliminar</a>
                            {% endif %}
                        </td>
                    </tr>
                </tbody>
                {% endfor %}
            </table>

            <!-- Importar el Paginador -->
            <hr class="my-5">
            <div>
                {% include 'core/paginacion.html' %}
            </div>

        </div>
    </div>
</div>
{% endblock %}